version: '3'
services:

  nginx:
    container_name: nginx
    volumes:
     - wordpress_vol:/var/www/wordpres
    networks:
      - inception
    depends_on:
     - wordpress
    restart: on-failure
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    env_file: .env
    ports:
      - "443:443"   

  mariadb:
    container_name: mariadb
    volumes:
     - mariadb_vol:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
    expose:
     - "3306"
    env_file:
      .env

  wordpress:
    container_name: wordpress
    volumes:
     - wordpress_vol:/var/www/wordpress
    env_file: .env
    networks:
      - inception
    restart: on-failure
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
    depends_on:
     - mariadb
    expose:
     - "9000"

volumes:
  wordpress_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/smunio/inception_vol/wordpress'
  mariadb_vol:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/smunio/inception_vol/mariadb'

networks:
  inception:
    driver: bridge
